name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ^20

      - name: Install Dependency
        run: yarn install

      - name: Run Lint
        run: yarn run lint

  coverage:
    needs: [lint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ^20

      - name: Install Dependency
        run: yarn install

      - name: Run Coverage
        run: yarn run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [^20]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependency
        run: yarn install

      - name: Run Unit test
        run: yarn run test

      - name: Run Build
        run: yarn run build

  semantic-release:
    needs: [lint, test, coverage]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ^20

      - name: Run semantic-release
        if: github.repository == 'casbin/casbin-core' && github.event_name == 'push'
        run: |
          yarn install
          yarn run build
          yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
